spring:
  application:
    name: revision
    group: SpringFramework
  server:
    port: 8080


logging:
  level:
    root: INFO
  file:
    name: logs/demo.log
  config: classpath:log4j2.xml


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/mananger"
  endpoint:
    health:
      show-details: "always"
      show-components: "always"
    info:
      show-details: "always"
    shutdown:
      access: "unrestricted"
    heapdump:
      access: unrestricted